cfg:
  compute_eval_loss: true
  labels:
  - ' '
  - a
  - b
  - c
  - d
  - e
  - f
  - g
  - h
  - i
  - j
  - k
  - l
  - m
  - 'n'
  - o
  - p
  - q
  - r
  - s
  - t
  - u
  - v
  - w
  - x
  - 'y'
  - z
  - ''''
  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
  model_defaults:
    enc_hidden: 4
    pred_hidden: 4
  encoder:
    _target_: nemo.collections.asr.modules.ConvASREncoder
    feat_in: 64
    activation: relu
    conv_mask: true
    jasper:
    - filters: 4
      repeat: 1
      kernel:
      - 1
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: false
      separable: true
      se: true
      se_context_size: -1
    - filters: 4
      repeat: 1
      kernel:
      - 1
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: false
      separable: true
      se: true
      se_context_size: -1
    - filters: 4
      repeat: 1
      kernel:
      - 1
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: false
      separable: true
      se: true
      se_context_size: -1
    - filters: 4
      repeat: 1
      kernel:
      - 1
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: false
      separable: true
      se: true
      se_context_size: -1
    - filters: 4
      repeat: 1
      kernel:
      - 1
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: false
      separable: true
      se: true
      se_context_size: -1
    - filters: 4
      repeat: 1
      kernel:
      - 1
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: false
      separable: true
      se: true
      se_context_size: -1
    - filters: 4
      repeat: 1
      kernel:
      - 1
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: false
      separable: true
      se: true
      se_context_size: -1
    - filters: 4
      repeat: 1
      kernel:
      - 1
      stride:
      - 1
      dilation:
      - 1
      dropout: 0.0
      residual: false
      separable: true
      se: true
      se_context_size: -1
  decoder:
    _target_: nemo.collections.asr.modules.RNNTDecoder
    prednet:
      pred_hidden: 4
      pred_rnn_layers: 1
  joint:
    _target_: nemo.collections.asr.modules.RNNTJoint
    jointnet:
      joint_hidden: 4
      activation: relu
  decoding:
    strategy: greedy_batch
    greedy:
      max_symbols: 30
  loss:
    loss_name: default
    warprnnt_numba_kwargs:
      fastemit_lambda: 0.001
  aux_ctc:
    ctc_loss_weight: 0.3
    use_cer: false
    ctc_reduction: mean_batch
    decoder:
      _target_: nemo.collections.asr.modules.ConvASRDecoder
      feat_in: null
      num_classes: 28
      vocabulary:
      - ' '
      - a
      - b
      - c
      - d
      - e
      - f
      - g
      - h
      - i
      - j
      - k
      - l
      - m
      - 'n'
      - o
      - p
      - q
      - r
      - s
      - t
      - u
      - v
      - w
      - x
      - 'y'
      - z
      - ''''
    decoding:
      strategy: greedy_batch
      preserve_alignments: null
      compute_timestamps: null
      word_seperator: ' '
      segment_seperators:
      - .
      - '!'
      - '?'
      segment_gap_threshold: null
      ctc_timestamp_type: all
      batch_dim_index: 0
      greedy:
        preserve_alignments: false
        compute_timestamps: false
        preserve_frame_confidence: false
        confidence_method_cfg:
          name: entropy
          entropy_type: tsallis
          alpha: 0.33
          entropy_norm: exp
          temperature: DEPRECATED
      beam:
        beam_size: 4
        search_type: default
        preserve_alignments: false
        compute_timestamps: false
        return_best_hypothesis: true
        beam_alpha: 1.0
        beam_beta: 0.0
        kenlm_path: null
        flashlight_cfg:
          lexicon_path: null
          boost_path: null
          beam_size_token: 16
          beam_threshold: 20.0
          unk_weight: -.inf
          sil_weight: 0.0
        pyctcdecode_cfg:
          beam_prune_logp: -10.0
          token_min_logp: -5.0
          prune_history: false
          hotwords: null
          hotword_weight: 10.0
      wfst:
        beam_size: 4
        search_type: riva
        return_best_hypothesis: true
        preserve_alignments: false
        compute_timestamps: false
        decoding_mode: nbest
        open_vocabulary_decoding: false
        beam_width: 10.0
        lm_weight: 1.0
        device: cuda
        arpa_lm_path: null
        wfst_lm_path: null
        riva_decoding_cfg: {}
        k2_decoding_cfg:
          search_beam: 20.0
          output_beam: 10.0
          min_active_states: 30
          max_active_states: 10000
      confidence_cfg:
        preserve_frame_confidence: false
        preserve_token_confidence: false
        preserve_word_confidence: false
        exclude_blank: true
        aggregation: min
        tdt_include_duration: false
        method_cfg:
          name: entropy
          entropy_type: tsallis
          alpha: 0.33
          entropy_norm: exp
          temperature: DEPRECATED
      temperature: 1.0
  interctc:
    loss_weights:
    - 0.1
    - 0.3
    apply_at_layers:
    - 2
    - 4
  optim:
    name: adamw
