name: &name NeuralTextNormalization

# Tagger
tagger_pretrained_model: null

tagger_trainer:
  gpus: 1        # the number of gpus, 0 for CPU
  num_nodes: 1
  max_epochs: 5  # the number of training epochs
  checkpoint_callback: false  # provided by exp_manager
  logger: false  # provided by exp_manager

tagger_model:
  transformer: distilroberta-base
  tokenizer: ${tagger_model.transformer}
  nemo_path: ${tagger_exp_manager.exp_dir}/tagger_model.nemo # exported .nemo path

  optim:
    name: adamw
    lr: 5e-5
    weight_decay: 0.01

    sched:
      name: WarmupAnnealing

      # pytorch lightning args
      monitor: val_sentence_accuracy
      reduce_on_plateau: false

      # scheduler config override
      warmup_steps: null
      warmup_ratio: 0.1
      last_epoch: -1

tagger_exp_manager:
  exp_dir: exps # where to store logs and checkpoints
  name: tagger_training # name of experiment
  create_tensorboard_logger: True
  create_checkpoint_callback: True
  checkpoint_callback_params:
    save_top_k: 3
    monitor: "val_sentence_accuracy"
    mode: "max"
    save_best_model: true
    always_save_nemo: true

# Decoder
decoder_pretrained_model: null

decoder_trainer:
  gpus: 1 # the number of gpus, 0 for CPU
  num_nodes: 1
  checkpoint_callback: false  # provided by exp_manager
  logger: false  # provided by exp_manager

decoder_model:
  transformer: t5-base
  tokenizer: ${decoder_model.transformer}
  nemo_path: ${decoder_exp_manager.exp_dir}/decoder_model.nemo # exported .nemo path

decoder_exp_manager:
  exp_dir: exps # where to store logs and checkpoints
  name: decoder_training # name of experiment
  create_tensorboard_logger: True
  create_checkpoint_callback: True

# Data
data:
  base_dir: /NeMo/google_en # /path/to/data

  train_ds:
    data_path: ${data.base_dir}/train.tsv
    batch_size: 64
    shuffle: true
    do_basic_tokenize: false

  validation_ds:
    data_path: ${data.base_dir}/dev.tsv
    batch_size: 64
    shuffle: false
    do_basic_tokenize: false

  test_ds:
    data_path: ${data.base_dir}/test.tsv
    batch_size: 64
    shuffle: false
