type: nemo.collections.asr.inference.utils.simulstream_pipeline_adapter.NeMoStreamingPipelineAdapter
speech_chunk_size: 4.8
detokenizer_type: simuleval
latency_unit: word
reference_manifest: /home/lgrigoryan/data/iwslt2026/acl_6060/dev/manifests/manifest_en_to_de.jsonl
asr:
  model_name: nvidia/parakeet-tdt-0.6b-v2
  device: cuda
  device_id: 0
  compute_dtype: bfloat16
  use_amp: false
  decoding:
    strategy: greedy_batch
    preserve_alignments: false
    fused_batch_size: -1
    greedy:
      use_cuda_graph_decoder: true
      enable_per_stream_biasing: true
      preserve_frame_confidence: false
      max_symbols: 10
      ngram_lm_model: null
      ngram_lm_alpha: 0.0
      boosting_tree:
        model_path: null
        key_phrases_file: null
        key_phrases_list: null
        key_phrase_items_list: null
        source_lang: en
      boosting_tree_alpha: 0.0
  per_stream_biasing_defaults:
    boosting_model_alpha: 1.0
    boosting_model_cfg:
      bpe_mode: case_insensitive
      var_bpe_scoring_temp: 10.0
itn:
  input_case: lower_cased
  whitelist: null
  overwrite_cache: false
  max_number_of_permutations_per_split: 729
  left_padding_size: 4
  batch_size: 32
  n_jobs: 16
nmt:
  model_name: utter-project/EuroLLM-1.7B-Instruct
  source_language: English
  target_language: German
  waitk: -1
  device: cuda
  device_id: 1
  batch_size: 16
  llm_params:
    dtype: auto
    seed: 42
    gpu_memory_utilization: 0.85
    max_model_len: 4096
  sampling_params:
    max_tokens: 100
    temperature: 0.0
    top_p: 0.9
    seed: 42
confidence:
  exclude_blank: true
  aggregation: mean
  method_cfg:
    name: entropy
    entropy_type: tsallis
    alpha: 0.5
    entropy_norm: exp
endpointing:
  stop_history_eou: 800
  residue_tokens_at_end: 2
streaming:
  sample_rate: 16000
  batch_size: 256
  left_padding_size: 1.6
  right_padding_size: 1.6
  chunk_size: 4.8
  word_boundary_tolerance: 4
  request_type: feature_buffer
  stateful: true
  padding_mode: right
matmul_precision: high
log_level: 20
pipeline_type: buffered
asr_decoding_type: rnnt
audio_file: null
output_filename: null
output_dir: null
enable_itn: false
enable_nmt: true
asr_output_granularity: segment
cache_dir: null
lang: null
return_tail_result: false
calculate_wer: true
calculate_bleu: true
warmup_steps: 0
run_steps: 1
metrics:
  asr:
    gt_text_attr_name: text
    clean_groundtruth_text: false
    langid: en
    use_cer: false
    ignore_capitalization: true
    ignore_punctuation: true
    strip_punc_space: false
  nmt:
    gt_text_attr_name: answer
    ignore_capitalization: false
    ignore_punctuation: false
    strip_punc_space: false
