comment: false
coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 0%
        base: auto
        if_ci_failed: error
        paths:
          - "nemo/export"
fixes:
  - "/workspace/::"
