
bot_prompt: "You are a helpful AI agent named Lisa. Start by greeting the user warmly and introducing yourself within one sentence. Your answer should be concise and to the point. You might also see speaker tags (<speaker_0>, <speaker_1>, etc.) in the user context. You should respond to the user based on the speaker tag and the context of that speaker. Do not include the speaker tags in your response, use them only to identify the speaker."


transport:
  audio_out_10ms_chunks: 8

vad:
  type: silero
  confidence: 0.6
  start_secs: 0.1
  stop_secs: 0.8
  min_volume: 0.4

stt:
  type: nemo
  model: "/media/data3/pretrained_models/nemo_asr/stt_en_fastconformer_hybrid_large_streaming_80ms.nemo"  # "nvidia/stt_en_fastconformer_hybrid_large_streaming_multi"
  device: "cuda"
  att_context_size: [70, 1]
  frame_len_in_secs: 0.08  # default for FastConformer, do not change

diar:
  type: nemo
  enabled: true
  model: "/home/heh/codes/niva-kunal/im417-normNA-ft3-mem14_epoch23-36.apr23_2025.nemo"
  device: "cuda"
  threshold: 0.4
  frame_len_in_secs: 0.08  # default for FastConformer, do not change

turn_taking:
  max_buffer_size: 2

llm:
  type: hf
  model: "/media/data/cache2/meta-llama/Meta-Llama-3-8B-Instruct"  # "meta-llama/Meta-Llama-3-8B-Instruct"
  device: "cuda"
  temperature: 0.7
  max_tokens: 128
  top_p: 0.9

tts:
  type: nemo
  model: fastpitch-hifigan
  fastpitch_model: "/media/data/cache2/nvidia/tts_en_fastpitch/tts_en_fastpitch.nemo"  # "nvidia/tts_en_fastpitch"
  hifigan_model: "/media/data/cache2/nvidia/tts_hifigan/tts_hifigan.nemo"  # "nvidia/tts_hifigan"
  device: "cuda"
  extra_separator: ":,?!"
