env:
    random_seed: 42
    save_git_hash: True

engine:    
    model_path: null  
    pretrained_name: null

    inference_mode: 
        mode: offline # choose from offline, chunked or offline_by_chunked
        chunk_len_in_secs: 1.6 #null # Need to specify if use buffered inference (default for offline_by_chunked is 20)
        total_buffer_in_secs: 4 #null # Need to specify if use buffered inference (default for offline_by_chunked is 22)
        model_stride: 4 # Model downsampling factor, 8 for Citrinet models and 4 for Conformer models
    
    test_ds:
        manifest_filepath: null
        sample_rate: 16000
        batch_size: 32
        
        augmentor:
          silence:
            prob: 0.8
            min_start_silence_secs: 0
            max_start_silence_secs: 5
            min_end_silence_secs: 0
            max_end_silence_secs: 5
            
          noise:
            manifest_path: null
            prob: 0.8
            min_snr_db: 0
            max_snr_db: 15

    output_filename: null

analyst:
    metric_calculator:
        clean_groundtruth_text: True
        output_filename: null # specify it if wanna skip engine and use previously generated manifest
        use_cer: False

    metadata:
        duration: 
            exec: True
            slot: [[0,2],[2,5],[5,10],[10,20],[20,100000]]
            wer_each_class: False #True # whether to save wer for each class.
            
        gender:
            exec: False
            slot: [["m"]]
            wer_each_class: True
            
        speaker:
            exec: True
            wer_each_class: False
            
        age:
            exec: False
            slot: null
            wer_each_class: False
            
        emotion: 
            exec: True
            slot: [['happy','laugh'],['neural'],['sad','cry']]
            wer_each_class: False
                 
writer:
    report_filename: null