name: p_tuning_squad_t5

trainer:
  devices: 1
  accelerator: gpu
  num_nodes: 1
  precision: 16
  logger: False 
  enable_checkpointing: False
  replace_sampler_ddp: False
  max_epochs: 10
  max_steps: 100
  log_every_n_steps: 10
  val_check_interval: 20
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  resume_from_checkpoint: null 

exp_manager:
  explicit_log_dir: null
  exp_dir: null
  name: ${name}
  create_wandb_logger: False
  wandb_logger_kwargs:
    project: null
    name: null
  resume_if_exists: True
  resume_ignore_no_checkpoint: True
  create_checkpoint_callback: True
  checkpoint_callback_params:
    monitor: val_loss
    save_top_k: 1
    mode: min
    save_nemo_on_train_end: True # Should be false, correct prompt learning model file is saved at model.virtual_prompt_save_path set below
    filename: "megatron_t5_adapter_tune--{${exp_manager.checkpoint_callback_params.monitor}:.3f}-{step}"
    model_parallel_size: ${model.tensor_model_parallel_size}
    save_best_model: True

model:
  seed: 1234
  virtual_prompt_save_path: ${name}.nemo # .nemo filename/absolute path to where the virtual prompt model parameters will be saved
  virtual_prompt_style: 'no-prompts' #'prompt-tuning' # adapter tuning requires no virtual prompts
  gradient_as_bucket_view: false
  tensor_model_parallel_size: 1
  pipeline_model_parallel_size: 1 
  encoder_seq_length: 2048
  global_batch_size: 8
  micro_batch_size: 8
  
  restore_path: null # Path to an existing p-tuned/prompt tuned .nemo model you wish to add new tasks to or run inference with
  pretrained_language_model_path: ??? # Path to the pretrained T5 language model .nemo file, always required
  existing_tasks: []
  new_tasks: ["squad"] 

  task_templates: 
  - taskname: "squad" 
    prompt_template: "{context} {question} {answer}" 
    total_virtual_tokens: 0
    virtual_token_splits: [] 
    truncate_field: context
    answer_field: answer

  - taskname: "rte" 
    prompt_template: "sentence1: {premise} sentence2: {hypothesis} Answer: {answer}" 
    total_virtual_tokens: 0
    virtual_token_splits: []
    truncate_field: null
    answer_only_loss: True
    answer_field: "answer"

  adapter_tuning:
    type: 'parallel_adapter' # this should be either 'parallel_adapter' or 'linear_adapter'
    adapter_dim: 50
    adapter_dropout: 0.1
    norm_position: 'pre' # This can be set to 'pre' or 'post', 'pre' is normally what is used.
    column_init_method: 'xavier' # IGNORED if linear_adapter is used, options: xavier, zero or normal
    row_init_method: 'zero' # IGNORED if linear_adapter is used, options: xavier, zero or normal
    norm_type: 'mixedfusedlayernorm' # IGNORED if layer_adapter is used,  options are ['layernorm', 'mixedfusedlayernorm']

  data:
    train_ds: ["data/squad_train.jsonl"]
    validation_ds: ["data/squad_val.jsonl"]
    add_eos: True
    shuffle: True
    num_workers: 8
    pin_memory: True


  optim:
    name: fused_adam
    lr: 1e-3
    weight_decay: 0.01 
    betas: 
    - 0.9
    - 0.98
    sched:
      name: CosineAnnealing
      warmup_steps: 50
      constant_steps: 0
      min_lr: 0.0
      monitor: val_loss
      reduce_on_plateau: false
  

