# @package _group_
dataset:
  _target_: "nemo.collections.tts.torch.data.VocoderDataset"
  manifest_filepath: ${train_dataset}
  sample_rate: ${sample_rate}
  n_segments: 8192
  max_duration: null
  min_duration: 0.75
dataloader_params:
  drop_last: false
  shuffle: true
  batch_size: 16
  num_workers: 4
