L0_Unit_Tests_GPU: |
  NEMO_NUMBA_MINVER=0.53 pytest -m "not pleasefixme" --with_downloads
L0_Unit_Tests_CPU: |
  CUDA_VISIBLE_DEVICES="" NEMO_NUMBA_MINVER=0.53 pytest -m "not pleasefixme" --cpu --with_downloads --relax_numba_compat
L0_Setup_Test_Data_And_Models: |
  python -m tests.setup --save_dir /home/TestData/nlp
