name: "MelGan"
sample_rate: 22050
n_fft: 1024
fmax: null
pad_value: -11.52
train_dataset: ???
validation_datasets: ???
n_mels: 80

model:
  init_adv_lambda: 2.5
  increase_lambda: False
  pqmf: False

  train_ds:
    dataset:
      _target_: "nemo.collections.tts.data.datalayers.AudioDataset"
      manifest_filepath: ${train_dataset}
      max_duration: null
      min_duration: 0.75
      n_segments: 16384
      trim: false
    dataloader_params:
      drop_last: false
      shuffle: true
      batch_size: 64
      num_workers: 4


  validation_ds:
    dataset:
      _target_: "nemo.collections.tts.data.datalayers.AudioDataset"
      manifest_filepath: ${validation_datasets}
      max_duration: null
      min_duration: 0.75
      n_segments: -1
      trim: false
    dataloader_params:
      drop_last: false
      shuffle: false
      batch_size: 13
      num_workers: 4

  preprocessor:
    _target_: nemo.collections.asr.parts.features.FilterbankFeatures
    dither: 0.0
    frame_splicing: 1
    nfilt: ${n_mels}
    highfreq: ${fmax}
    log: true
    log_zero_guard_type: clamp
    log_zero_guard_value: 1e-05
    lowfreq: 0
    mag_power: 1.0
    n_fft: ${n_fft}

    n_window_size: 1024
    n_window_stride: 256

    normalize: null
    pad_to: 0
    pad_value: ${pad_value}
    preemph: null
    sample_rate: ${sample_rate}
    stft_conv: false
    window: hann

  gen:
    in_channels: ${n_mels}               # Number of input channels.
    out_channels: 1               # Number of output channels.
    kernel_size: 7                # Kernel size of initial and final conv layers.
    channels: 512                 # Initial number of channels for conv layers.
    upsample_scales: [8, 4, 4, 2]    # List of Upsampling scales.
    stack_kernel_size: 3          # Kernel size of dilated conv layers in residual stack.
    stacks: 4                     # Number of stacks in a single residual stack module.
    use_weight_norm: True         # Whether to use weight normalization.
    use_causal_conv: False

  disc:
    out_channels: 1                   # Number of output channels.
    kernel_sizes: [5, 3]              # List of kernel size.
    channels: 16                      # Number of channels of the initial conv layer.
    input_lengths: [256, 512, 1024, 2048, 4096]
    max_downsample_channels: 512      # Maximum number of channels of downsampling layers.
    downsample_scales: [4, 4, 4]      # List of downsampling scales.
    nonlinear_activation: "LeakyReLU" # Nonlinear activation function.
    nonlinear_activation_params:      # Parameters of nonlinear activation function.
        negative_slope: 0.2
    use_weight_norm: True             # Whether to use weight norm.
    use_spectral_norm: False             # Whether to use weight norm.

  loss:
    fft_sizes: [1024, 2048, 512]
    hop_sizes: [120, 240, 50]
    win_lengths: [600, 1200, 240]
    window: "hann_window"

trainer:
  gpus: 1 # number of gpus
  max_epochs: ???
  num_nodes: 1
  accelerator: ddp
  accumulate_grad_batches: 1
  checkpoint_callback: False  # Provided by exp_manager
  logger: False  # Provided by exp_manager
  flush_logs_every_n_steps: 1000
  log_every_n_steps: 200
  check_val_every_n_epoch: 150

exp_manager:
  exp_dir: null
  name: ${name}
  create_tensorboard_logger: True
  create_checkpoint_callback: True
  checkpoint_callback_params:
    save_top_k: null
    monitor: null
    save_last: null
