dataset:
  _target_: "nemo.collections.tts.torch.data_ssl_vocoder.SSLVocoderDataset"
  manifest_filepath: ${validation_datasets}
  ssl_model_type: ${ssl_model_type}
  ssl_model_ckpt_path: ${ssl_model_ckpt_path}
  ssl_content_emb_type: ${ssl_content_emb_type}
  sample_rate: ${sample_rate}
  n_segments: ${val_n_segments}
  max_duration: ${val_max_duration}
  min_duration: ${val_min_duration}
  pitch_conditioning: ${pitch_conditioning}
  pitch_mean: ${pitch_mean}
  pitch_std: ${pitch_std}
  normalize_pitch: ${normalize_pitch}
  sup_data_dir: ${sup_data_dir}
  data_caching: ${data_caching}
  normalize_content: ${normalize_content}
  use_speakerwise_stats: ${use_speakerwise_stats}
  stat_samples_per_speaker: ${stat_samples_per_speaker}
dataloader_params:
  drop_last: false
  shuffle: false
  batch_size: 16
  num_workers: 1
  pin_memory: true
  