dataset:
  _target_: "nemo.collections.tts.torch.data.VocoderDataset"
  manifest_filepath: ${validation_datasets}
  sample_rate: ${sample_rate}
  n_segments: 66048
  max_duration: null
  min_duration: 3
dataloader_params:
  drop_last: false
  shuffle: false
  batch_size: 16
  num_workers: 1
