name: &name itn
lang: ???        # e.g. 'ru', 'en'

# Pretrained Nemo Models
pretrained_model: null

trainer:
  devices: 1 # the number of gpus, 0 for CPU
  num_nodes: 1
  max_epochs: 3  # the number of training epochs
  checkpoint_callback: false  # provided by exp_manager
  logger: false  # provided by exp_manager
  accumulate_grad_batches: 1 # accumulates grads every k batches
  gradient_clip_val: 0.0
  precision: 32 # Should be set to 16 for O1 and O2 to enable the AMP.
  accelerator: gpu
  strategy: ddp
  log_every_n_steps: 1  # Interval of logging.
  val_check_interval: 1.0  # Set to 0.25 to check 4 times per epoch, or an int for number of iterations
  resume_from_checkpoint: null # The path to a checkpoint file to continue the training, restores the whole state including the epoch, step, LR schedulers, apex, etc.

model:
  do_training: true
  label_map: ./label_map.txt
  semiotic_classes: ./semiotic_classes.txt
  transformer: bert-base-uncased  # For ru, try DeepPavlov/rubert-base-cased | For de or multilingual, try bert-base-multilingual-cased
  max_sequence_len: 128
  lang: ${lang}
  hidden_size: 768

  optim:
    name: adamw
    lr: 3e-5      #3e-4   3e-3  1e-4
    weight_decay: 0.1

    sched:
      name: WarmupAnnealing                      

      # pytorch lightning args
      monitor: val_loss
      reduce_on_plateau: false

      # scheduler config override
      #warmup_steps: 4500
      warmup_ratio: 0.1
      last_epoch: -1

  language_model:
    pretrained_model_name: bert-base-uncased
    lm_checkpoint: null
    config_file: null # json file, precedence over config
    config: null

  tokenizer:
    tokenizer_name: ${model.language_model.pretrained_model_name} # or sentencepiece
    vocab_file: null # path to vocab file
    tokenizer_model: null # only used if tokenizer is sentencepiece
    special_tokens: null

exp_manager:
  exp_dir: nemo_experiments # where to store logs and checkpoints
  name: training # name of experiment
  create_tensorboard_logger: True
  create_checkpoint_callback: True
  checkpoint_callback_params:
    save_top_k: 3
    monitor: "val_loss"
    mode: "min"

tokenizer:
    tokenizer_name: ${model.transformer} # or sentencepiece
    vocab_file: null # path to vocab file
    tokenizer_model: null # only used if tokenizer is sentencepiece
    special_tokens: null

# Data
data:
  train_ds:
    data_path: ./train.tsv # provide the full path to the file
    batch_size: 8
    shuffle: true
    max_insts: -1 # Maximum number of instances (-1 means no limit)
    use_cache: false # uses a cache to store the processed dataset, you may use it for large datasets for speed up (especially when using multi GPUs)
    num_workers: 3
    pin_memory: false
    drop_last: false
    use_tarred_dataset: False # if true tar_metadata_file will be used
    tar_metadata_file: null # metadata for tarred dataset. A JSON file containing the list of tar_files in "text_tar_filepaths" field
    tar_shuffle_n: 100 # How many samples to look ahead and load to be shuffled

  validation_ds:
    data_path: ./valid.tsv # provide the full path to the file. Provide multiple paths to run evaluation on multiple datasets
    batch_size: 8
    shuffle: false
    max_insts: -1 # Maximum number of instances (-1 means no limit)
    use_cache: false # uses a cache to store the processed dataset, you may use it for large datasets for speed up (especially when using multi GPUs)
    num_workers: 3
    pin_memory: false
    drop_last: false

  test_ds:
    data_path: ./test.tsv # provide the full path to the file
    batch_size: 8
    shuffle: false
    use_cache: false # uses a cache to store the processed dataset, you may use it for large datasets for speed up (especially when using multi GPUs)
    num_workers: 3
    pin_memory: false
    drop_last: false
    errors_log_fp: errors.txt # Path to the file for logging the errors

# Inference
inference:
  from_file: null # Path to the raw text, no labels required. Each sentence on a separate line
  out_file: null # Path to the output file
  batch_size: 16 # batch size for inference.from_file
