cfg:
  mcore_gpt: true
  micro_batch_size: 4
  global_batch_size: 8
  rampup_batch_size: null
  tensor_model_parallel_size: 1
  pipeline_model_parallel_size: 1
  virtual_pipeline_model_parallel_size: null
  encoder_seq_length: 128
  max_position_embeddings: 128
  num_layers: 8
  hidden_size: 256
  ffn_hidden_size: 3072
  num_attention_heads: 8
  init_method_std: 0.02
  use_scaled_init_method: true
  hidden_dropout: 0.1
  attention_dropout: 0.1
  ffn_dropout: 0.0
  kv_channels: null
  apply_query_key_layer_scaling: false
  normalization: layernorm1p
  layernorm_epsilon: 1.0e-05
  do_layer_norm_weight_decay: false
  make_vocab_size_divisible_by: 128
  pre_process: true
  post_process: true
  persist_layer_norm: true
  bias: true
  activation: gelu
  headscale: false
  transformer_block_type: pre_ln
  openai_gelu: false
  normalize_attention_scores: true
  position_embedding_type: learned_absolute
  rotary_percentage: 1.0
  attention_type: multihead
  share_embeddings_and_output_weights: true
  overlap_p2p_comm: false
  batch_p2p_comm: true
  seq_len_interpolation_factor: null
  num_query_groups: null
  tokenizer:
    library: megatron
    type: GPT2BPETokenizer
    model: null
    vocab_file: null
    merge_file: null
    delimiter: null
    sentencepiece_legacy: false
  native_amp_init_scale: 4294967296
  native_amp_growth_interval: 1000
  hysteresis: 2
  fp32_residual_connection: false
  fp16_lm_cross_entropy: false
  megatron_amp_O2: false
  grad_allreduce_chunk_size_mb: 125
  grad_div_ar_fusion: true
  gradient_accumulation_fusion: false
  bias_activation_fusion: true
  bias_dropout_add_fusion: true
  masked_softmax_fusion: true
  get_attention_mask_from_fusion: true
  apply_rope_fusion: false
  seed: 1234
  resume_from_checkpoint: null
  use_cpu_initialization: false
  onnx_safe: false
  apex_transformer_log_level: 30
  gradient_as_bucket_view: true
  sync_batch_comm: false
  nccl_communicator_config_path: null
  fsdp: false
  fsdp_sharding_strategy: full
  fsdp_grad_reduce_dtype: fp32
  fsdp_sharded_checkpoint: false
  activations_checkpoint_granularity: null
  activations_checkpoint_method: null
  activations_checkpoint_num_layers: null
  num_micro_batches_with_partial_activation_checkpoints: null
  activations_checkpoint_layers_per_pipeline: null
  sequence_parallel: false
  transformer_engine: false
  fp8: false
  fp8_e4m3: false
  fp8_hybrid: true
  fp8_margin: 0
  fp8_interval: 1
  fp8_amax_history_len: 1024
  fp8_amax_compute_algo: max
  reduce_amax: true
  use_emha: false
  ub_tp_comm_overlap: false
  ub_tp_comm_overlap_cfg: null
  use_flash_attention: false
  cpu_offloading: false
  cpu_offloading_num_layers: 7
  cpu_offloading_activations: true
  cpu_offloading_weights: true
  sharp: false
  enable_megatron_timers: false
  megatron_timer_kwargs:
    log_every_n_steps: 10
    log_mode: minmax
    barrier: false
  data:
    data_prefix:
    - 1.0
    - /home/data/test_text_document
    index_mapping_dir: null
    data_impl: mmap
    splits_string: 900,50,50
    seq_length: 128
    skip_warmup: true
    num_workers: 2
    dataloader_type: single
    reset_position_ids: false
    reset_attention_mask: false
    eod_mask_loss: false
    validation_drop_last: true
    no_seqlen_plus_one_input_tokens: false
    pad_samples_to_global_batch_size: false
    shuffle_documents: true
    exchange_indices_distributed: false
    mock_dataset: false
    add_fim: true
    fim:
      extra_tokens:
        prefix: fim_prefix
        middle: fim_middle
        suffix: fim_suffix
        pad: fim_pad
        eod: endoftext
  nsys_profile:
    enabled: false
    start_step: 10
    end_step: 10
    ranks:
    - 0
    gen_shape: false
  optim:
    name: fused_adam
    lr: 0.0002
    weight_decay: 0.01
    betas:
    - 0.9
    - 0.98
    sched:
      name: CosineAnnealing
      warmup_steps: 1
      constant_steps: 1
      min_lr: 8.0e-05
  gc_interval: 0
  name: megatron_gpt_full_te_layer_autocast
  precision: 16-mixed
