# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

data:
  camera_front_wide_120fov:
    # 3840 × 2160  -> (bottom Crop + left right side crop) 3840 * 2160  -> (resize) 512 * 320
    crop_h: 2160
    crop_w: 3840
    size_h: 1080
    size_w: 1920
    fps: 30
  camera_cross_left_120fov:
    crop_h: 2160
    crop_w: 3840
    size_h: 1080
    size_w: 1920
    fps: 30
  camera_cross_right_120fov:
    crop_h: 2160
    crop_w: 3840
    size_h: 1080
    size_w: 1920
    fps: 30
  camera_front_tele_30fov:
    crop_h: 2160
    crop_w: 3840
    size_h: 1080
    size_w: 1920
    fps: 30
  camera_front_tele_sat_30fov:
    crop_h: 2160
    crop_w: 3840
    size_h: 1080
    size_w: 1920
    fps: 30
  camera_rear_tele_30fov:
    crop_h: 2160
    crop_w: 3840
    size_h: 1080
    size_w: 1920
    fps: 30
  camera_left_fisheye_200fov:
    # H8 1936x1216, H81 1920x1536
    # Crop width to the smaller of the two dimensions, scale
    crop_h: 1200
    crop_w: 1920
    size_h: 1080
    size_w: 1920
    fps: 30
  camera_rear_fisheye_200fov:
    # H8 1936x1216, H81 1920x1536
    crop_h: 1200
    crop_w: 1920
    size_h: 1080
    size_w: 1920
    fps: 30
  camera_right_fisheye_200fov:
    # H8 1936x1216, H81 1920x1536
    crop_h: 1200
    crop_w: 1920
    size_h: 1080
    size_w: 1920
    fps: 30
  camera_front_fisheye_200fov:
    # H8 1936x1216, H81 1920x1536
    crop_h: 1200
    crop_w: 1920
    size_h: 1080
    size_w: 1920
    fps: 30
  camera_rear_right_70fov:
    crop_h: 2160
    crop_w: 3840
    size_h: 1080
    size_w: 1920
    fps: 30
  camera_rear_left_70fov:
    crop_h: 2160
    crop_w: 3840
    size_h: 1080
    size_w: 1920
    fps: 30


conversion:
  name: AV2fps-1080x512
  strict: T1920
  dataset_attr: labels
  maxsize: 1e9
  maxcount: 4000