cfg:
  micro_batch_size: 4
  tensor_model_parallel_size: 1
  encoder_seq_length: 2048
  max_position_embeddings: 2048
  num_layers: 12
  hidden_size: 768
  ffn_hidden_size: 3072
  num_attention_heads: 12
  init_method_std: 0.02
  hidden_dropout: 0.1
  kv_channels: null
  apply_query_key_layer_scaling: true
  layernorm_epsilon: 1.0e-05
  make_vocab_size_divisible_by: 128
  pre_process: true
  post_process: true
  tokenizer:
    library: megatron
    type: GPT2BPETokenizer
    model: null
    vocab_file: null
    merge_file: null
  native_amp_init_scale: 4294967296
  native_amp_growth_interval: 1000
  fp32_residual_connection: false
  fp16_lm_cross_entropy: false
  seed: 1234
  use_cpu_initialization: false
  onnx_safe: false
  activations_checkpoint_method: null
  activations_checkpoint_num_layers: 1
  data:
    data_prefix: None
    data_impl: mmap
    splits_string: 900,50,50
    seq_length: 2048
    skip_warmup: true
    num_workers: 0
    dataloader_type: single
    reset_position_ids: false
    reset_attention_mask: false
    eod_mask_loss: false
    train_ds: boolq_prompt_tuning_train.jsonl
    valid_ds: boolq_prompt_tuning_val.jsonl
    batch_size: 32
  optim:
    name: fused_adam
    lr: 0.0002
    weight_decay: 0.01
    betas:
    - 0.9
    - 0.98
    sched:
      name: CosineAnnealing
      warmup_steps: 295
      constant_steps: 1000
      min_lr: 2.0e-06
  use_soft_prompts: true
  num_prompt_tokens: 50
  existing_prompt_tags:
  - RTE
  - Winogrande
  - BoolQ
  new_prompt_tags:
  - BoolQ
  new_prompt_init_text:
  - true false question answer reading comprehension
  new_prompt_init_methods:
  - text
