name: megatron_ptune_gpt

trainer:
  gpus: 2
  num_nodes: 1
  precision: 16
  logger: False # logger provided by exp_manager
  checkpoint_callback: False
  replace_sampler_ddp: False
  max_epochs: 3
  max_steps: null # consumed_samples = global_step * micro_batch_size * data_parallel_size * accumulate_grad_batches
  log_every_n_steps: 10
  val_check_interval: 300
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  resume_from_checkpoint: null # The path to a checkpoint file to continue the training, restores the whole state including the epoch, step, LR schedulers, apex, etc.


exp_manager:
  explicit_log_dir: null
  exp_dir: null
  name: megatron_ptune_gpt
  create_wandb_logger: False
  wandb_logger_kwargs:
    project: null
    name: null
  resume_if_exists: True
  resume_ignore_no_checkpoint: True
  create_checkpoint_callback: True
  checkpoint_callback_params:
    monitor: val_acc
    save_top_k: 2
    mode: max
    always_save_nemo: False # TODO: add support
    filename: 'megatron_gpt--{val_acc:.3f}-{step}'
    model_parallel_size: ${model.tensor_model_parallel_size}
    save_best_model: True

model:
  tensor_model_parallel_size: 1
  seed: 1234
  nemo_path: ptune_gpt_model.nemo # filename to save the model and associated artifacts to .nemo file
  use_lm_finetune: False # whether fine tune the language model
  pseudo_token: '[PROMPT]' # pseudo prompt tokens
  max_decode_length: null # max number of tokens length to decode, if set null, it will be inferred from data

  language_model:
    nemo_file: null

  prompt_encoder:
    template: [3, 3, 0]
    dropout: 0.0
    num_layers: 2

  data:
    train_ds:
      task_name: 'mnli'
      file_path: ???
      batch_size: 32
      shuffle: True
      num_workers: 8
      pin_memory: True
      max_seq_length: 512

    validation_ds:
      task_name: 'mnli'
      file_path: ???
      batch_size: 32
      shuffle: False
      num_workers: 8
      pin_memory: True
      max_seq_length: 512

    test_ds:
      task_name: 'mnli'
      file_path: ???
      batch_size: 32
      shuffle: False
      num_workers: 8
      pin_memory: True
      max_seq_length: 512

  optim:
    name: adam
    lr: 1e-5
    # optimizer arguments
    betas: [0.9, 0.999]
    weight_decay: 0.0005
    # scheduler setup
    sched:
      name: WarmupAnnealing
      # Scheduler params
      warmup_steps: null
      warmup_ratio: 0.1
      last_epoch: -1
      # pytorch lightning args
      monitor: val_loss
      reduce_on_plateau: false
