name: megatron_t5_glue_xnli_eval

trainer:
  gpus: 1
  num_nodes: 1
  accelerator: ddp
  precision: 16
  logger: False # logger provided by exp_manager
  checkpoint_callback: False
  replace_sampler_ddp: False
  log_every_n_steps: 10

exp_manager:
  explicit_log_dir: null
  exp_dir: null
  name: megatron_t5_glue_xnli_eval
  create_wandb_logger: False

model:
  restore_from_finetuned_path: ??? # Path to a finetuned T5 .nemo file
  tensor_model_parallel_size: 1
  gradient_as_bucket_view: True # Allocate gradients in a contiguous bucket to save memory (less fragmentation and buffer memory)
  megatron_amp_O2: False # Enable O2 optimization for megatron amp
  eval_languages: ['fr', 'de', 'en', 'es'] # List of languages to evaluate zero-shot XNLI performance.

  data:
    test_ds:
      task_name: 'xnli'
      file_path: ??? # Path to the TSV file for XNLI dev ex: '/raid/Data/GLUE/MNLI/dev_matched.tsv'
      batch_size: 32
      shuffle: False
      num_workers: 8
      pin_memory: True
      max_seq_length: 512
