vads_amount : 750000
vads_auth_mode : FULL
vads_auth_number : 220869
vads_auth_result : 00
vads_capture_delay : 0
vads_card_brand : AMEX
vads_card_number : 379218XXXXX1001
vads_payment_certificate : 1ad9b10e63c359501e93d4c3b058954fbbf34091
vads_ctx_mode : PRODUCTION
vads_currency : 978
vads_effective_amount : 750000
vads_effective_currency : 978
vads_site_id : 69313943
vads_trans_date : 20220808161218
vads_trans_id : 161218
vads_trans_uuid : 458485950ce94793a4f76395941e090e
vads_initial_issuer_transaction_identifier : 002686912209305
vads_validation_mode : 0
vads_version : V2
vads_warranty_result : 
vads_payment_src : EC
vads_ext_trans_id : 002686912209305
vads_cust_email : chris.sonon@trimech.com
vads_cust_id : 145351
vads_cust_status : COMPANY
vads_cust_name : Christopher Sonon
vads_cust_first_name : Christopher
vads_cust_last_name : Sonon
vads_cust_address : 4991 Lake Brook Drive  Suite 300
vads_cust_zip : 23060
vads_cust_city : Glen Allen
vads_cust_phone : 8656438394
vads_cust_state : Virginia
vads_cust_legal_name : TriMech
vads_tid : 001
vads_sequence_number : 1
vads_acquirer_network : AMEXGLOBAL
vads_contract_used : 9492624200
vads_trans_status : AUTHORISED
vads_expiry_month : 5
vads_expiry_year : 2024
vads_pays_ip : US
vads_presentation_date : 20220808161221
vads_effective_creation_date : 20220808161221
vads_occurrence_type : UNITAIRE
vads_operation_type : DEBIT
vads_result : 00
vads_extra_result : 
vads_card_country : 
vads_language : en
vads_hash : efd22f4f7d6ce583951656759c36032199925b5c8c87ad439447a4c2a782f0b3
vads_url_check_src : PAY
vads_action_mode : INTERACTIVE
vads_payment_config : SINGLE
vads_page_action : PAYMENT
vads_archival_reference_id : L22016121801
vads_threeds_enrolled : Y
vads_threeds_auth_type : CHALLENGE
vads_threeds_eci : 05
vads_threeds_xid : 
vads_threeds_cavvAlgorithm : 
vads_threeds_status : Y
vads_threeds_sign_valid : 
vads_threeds_error_code : 
vads_threeds_exit_status : 10
vads_threeds_cavv : AAACBkGSdwICIiAGhpJ3ED/2+hA=
signature : 7465202541766e7eac3646748e2fe3d55b4f2b5a