dataset:
  _target_: "nemo.collections.tts.torch.data.VocoderDataset"
  manifest_filepath: ${train_dataset}
  sample_rate: ${sample_rate}
  n_segments: 16384
  min_duration: 0.75
  load_precomputed_mel: true
  hop_length: ${n_window_stride}
dataloader_params:
  drop_last: false
  shuffle: true
  batch_size: 32
  num_workers: 4
