"project_dir: .\nname: SelfAlignmentPretrainingForMedicalEntityLinking\ntrainer:\n\
  \  gpus: 1\n  num_nodes: 1\n  max_epochs: 2\n  max_steps: null\n  accumulate_grad_batches:\
  \ 1\n  precision: 16\n  amp_level: O1\n  accelerator: ddp\n  gradient_clip_val:\
  \ 0.0\n  log_every_n_steps: 1\n  val_check_interval: 2\n  checkpoint_callback: false\n\
  \  logger: false\nmodel:\n  nemo_path: tiny_example_sap_bert_model.nemo\n  max_seq_length:\
  \ 128\n  language_model:\n    pretrained_model_name: bert-base-uncased\n    config_file:\
  \ null\n    config: null\n    lm_checkpoint: null\n  tokenizer:\n    tokenizer_name:\
  \ ${model.language_model.pretrained_model_name}\n    vocab_file: null\n    tokenizer_model:\
  \ null\n    do_lower_case: true\n  train_ds:\n    data_file: tiny_example_train_pairs.tsv\n\
  \    max_seq_length: ${model.max_seq_length}\n    batch_size: 8\n    shuffle: true\n\
  \    num_workers: 2\n    pin_memory: false\n    drop_last: false\n  validation_ds:\n\
  \    data_file: tiny_example_validation_pairs.tsv\n    max_seq_length: ${model.max_seq_length}\n\
  \    batch_size: 8\n    shuffle: false\n    num_workers: 2\n    pin_memory: false\n\
  \    drop_last: false\n  optim:\n    name: adam\n    lr: 3.0e-05\n    weight_decay:\
  \ 0.0\n    sched:\n      name: CosineAnnealing\n      warmup_steps: null\n     \
  \ warmup_ratio: 0.1\n      min_lr: 0.0\n      last_epoch: -1\nindex:\n  dims: 768\n\
  \  nlist: 2\n  top_n: 3\n  query_num_factor: 20\n  index_save_name: tiny_example_entity_linking_index\n\
  \  index_batch_size: 10\n  dataset:\n    name: tiny_example\n    data_file: tiny_example_index_data.tsv\n\
  \    max_seq_length: ${model.max_seq_length}\n    batch_size: 100\n    shuffle:\
  \ false\n    num_workers: 2\n    pin_memory: false\n    drop_last: false\n  idx_to_id:\
  \ idx_to_id.pkl\n  id_to_string: id_to_string.pkl\n  concept_id_save_name: tiny_example_concept_ids.pkl\n\
  \  embedding_save_name: tiny_example_concept_embeddings.hdf5\n  pca_embeddings_save_name:\
  \ null\n  apply_pca: false\n  pca: null\nexp_manager:\n  exp_dir: .\n  name: SelfAlignmentPretrainingTinyExample\n\
  \  create_tensorboard_logger: true\n  create_checkpoint_callback: true\nhydra:\n\
  \  run:\n    dir: .\n  job_logging:\n    root:\n      handlers: null\n"
