model: /lustre/fsw/portfolios/convai/users/nkarpov/armenian/checkpoints/135h-sp_ssl-init_bped-0.1--cs_oci_ord-bd1300xg8xn1--ms20000-ws7000-lr0.001_spe-1024--bf16--fc-l_hybrid_rnnt-ctc_bpe_ssl128.yaml.nemo
output_path: ./ 
return_predictions: False
#use_cer: False
decoder_type: null
att_context_size: null

predict_ds:
  manifest_filepath: [["/lustre/fsw/portfolios/convai/users/nkarpov/armenian/youtube/audio_manifest.json"]]
  sample_rate: 16000
  labels: ["labels"]
  trim_silence: false
  
  # Tarred dataset support
  is_tarred: false
  # tarred_audio_filepaths: [["/lustre/fsw/portfolios/convai/users/ntadevosyan/draco_data/datasets/pt/labeled_data/mls_tarred/bucket1/audio__OP_0..127_CL_.tar"],["/lustre/fsw/portfolios/convai/users/ntadevosyan/draco_data/datasets/pt/labeled_data/mls_tarred/bucket2/audio__OP_0..127_CL_.tar"],["/lustre/fsw/portfolios/convai/users/ntadevosyan/draco_data/datasets/pt/labeled_data/mls_tarred/bucket3/audio__OP_0..127_CL_.tar"],["/lustre/fsw/portfolios/convai/users/ntadevosyan/draco_data/datasets/pt/labeled_data/mls_tarred/bucket4/audio__OP_0..127_CL_.tar"]]
  tarred_shard_strategy: "scatter"
  shard_manifests: false
  shuffle: True
  
  # Optional
  int_values: null
  augmentor: null
  max_duration: null
  min_duration: null
  max_utts: 0
  blank_index: -1
  unk_index: -1
  normalize: false
  trim: true
  parser: "en"
  eos_id: null
  bos_id: null
  pad_id: 0
  use_start_end_token: false
  use_lhotse: true 
  return_sample_id: false
  
  # Bucketing params
  bucketing_strategy: "synced_randomized"
  bucketing_batch_size: null
  bucketing_weights: null
  
  # Optional callable function to parse manifest file
  manifest_parse_func: null
trainer:
  num_nodes: 4
