name: Bump Megatron Tag Template
on:
  workflow_call:
    inputs:
      nemo-target-branch:
        required: true
        type: string
        description: "The target branch to bump"
      mcore-target-branch:
        required: true
        type: string
        description: "The target branch to bump"
    secrets:
      PAT:
        required: true

jobs:
  update-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Merge weekly-bump-${{ inputs.nemo-target-branch }} back to base branch
        run: |
          git fetch origin ${{ inputs.nemo-target-branch }}

          # Try to checkout and pull existing branch, create new one if it doesn't exist
          if git ls-remote --exit-code origin weekly-bump-${{ inputs.nemo-target-branch }}; then
            git fetch origin weekly-bump-${{ inputs.nemo-target-branch }}
            git checkout weekly-bump-${{ inputs.nemo-target-branch }}
            git merge --no-ff ${{ inputs.nemo-target-branch }} -m "chore: Auto-merge ${{ inputs.nemo-target-branch }} into weekly-bump-${{ inputs.nemo-target-branch }}"
          else
            git checkout -b weekly-bump-${{ inputs.nemo-target-branch }} origin/${{ inputs.nemo-target-branch }}
          fi
          git push -u origin weekly-bump-${{ inputs.nemo-target-branch }}

  mcore:
    uses: NVIDIA/NeMo-FW-CI-templates/.github/workflows/_bump_yamlfile.yml@v0.27.1
    needs: [update-branch]
    with:
      source-repository: NVIDIA/Megatron-LM
      source-ref: ${{ inputs.mcore-target-branch }}
      yaml-path: '."vcs-dependencies"."megatron-lm".ref'
      file: requirements/manifest.json
      base-branch: weekly-bump-${{ inputs.nemo-target-branch }}
      cicd-labels: Run CICD,no-fail-fast
      pr-reviewers: ${{ inputs.pr-reviewers }}
    secrets:
      PAT: ${{ secrets.PAT }}
