name: 'ChangelogBuild'
on:
  push:
    tags:
      - '*'

jobs:
  changelog:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'NVIDIA/NeMo'

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          owner: "NVIDIA"
          repo: "NeMo"
          fromTag: "v1.4.0"
          toTag: "v1.5.1"
