name: 'ChangelogBuild'

env:
  FROM_TAG: "v1.4.0"


on:
  push:
    tags:
      - 'v*'

jobs:
  changelog:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Changelog
        id: github_tag
        uses: mikepenz/release-changelog-builder-action@v2.7.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration: ".github/workflows/config/changelog-config.json"
          owner: "NVIDIA"
          repo: "NeMo"
          fromTag: ${{ env.FROM_TAG }}
          toTag: "${{ github.ref_name:10 }}"

      - name: Print Changelog
        run: |
          echo "${{steps.github_tag.outputs.changelog}}"
          echo "--- DONE ---"
