name: CI-CPU

on:
  push:
    branches:
      - main
      - 'r1.**'

  pull_request:
    branches:
      - main
      - 'r1.**'

jobs:
  ci-cpu:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        container-ver:
          - 21.06-py3

    container:
      image: nvcr.io/nvidia/pytorch:${{ matrix.container-ver }}
      credentials:
        username: ${{ secrets.nvcr_user }}
        password: ${{ secrets.nvcr_token }}

    steps:
    - uses: actions/checkout@v2

    - name: Install test dependencies
      run:  |
        # install test requirements
        pip install -r requirements/requirements_test.txt

    - name: Check copyright headers
      run:  |
        python tests/check_copyright_header.py --dir .

    - name: Check style
      run: |
        python setup.py style

    - name: Install dependencies
      run: |
        # Install nemo requirements
        for f in $(ls requirements/requirements*.txt); do pip install --disable-pip-version-check -r $f; done

        # Install NeMo
        pip install -e ".[all]"

        # Update Conda
        conda install -c numba numba=0.53.1 -y

    - name: CPU Tests
      run: |
        pytest -m "not pleasefixme" --cpu --relax_numba_compat
