name: CI-ITN

on:
  push:
    branches:
      - '**tn**'

#    paths:
#      - 'nemo_text_preprocessing/**'
#      - 'tools/text_processing_deployment/**'
#      - 'tests/nemo_text_preprocessing/**'

  pull_request:
    branches:
      - '**tn**'

#    paths:
#      - 'nemo_text_preprocessing/**'
#      - 'tools/text_processing_deployment/**'
#      - 'tests/nemo_text_preprocessing/**'

jobs:
  ci-itn:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

#    - name: Update Conda
#      run: |
#        conda update -n base -c defaults conda -y
#        conda install conda-build -y
#        apt-get update && apt-get install -y --reinstall build-essential
#        apt-get install -y make libsndfile1 sox libfreetype6 ffmpeg swig

    - name: Build TN/ITN docker
      run: |
        cd tools/text_processing_deployment
        echo $PWD
        /bin/bash docker/build.sh
