name: CI-ITN

on:
  push:
    branches:
      - '**itn**'

  pull_request:
    branches:
      - '**itn**'

  schedule:
    # Run daily at 5:00 AM
    - cron: '0 5 * * *'

jobs:
  ci-itn:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        container-ver:
          - 21.06-py3

    container:
      image: nvcr.io/nvidia/pytorch:${{ matrix.container-ver }}
      credentials:
        username: ${{ secrets.nvcr_user }}
        password: ${{ secrets.nvcr_token }}

    steps:
    - uses: actions/checkout@v2

    - name: Install test dependencies
      run:  |
        # install test requirements
        pip install -r requirements/requirements_test.txt

    - name: Install dependencies
      run: |
        # Install ITN requirements
        /bin/bash nemo_text_processing/setup.sh

        # Install NeMo
        pip install -e "."

    - name: CPU Tests
      run: |
        pytest tests/nemo_text_processing/ -m "not pleasefixme" --cpu
