name: NeMo Unit Tests
on:
  workflow_call:
    inputs:
      test_to_run:
        required: true
        type: string

jobs:
  # L0: GPU unit tests
  L0_Unit_Tests_GPU_ASR:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'L0_Unit_Tests_GPU_ASR')
    with:
      RUNNER: self-hosted-azure-gpus-1
      TIMEOUT: 20
      IS_UNIT_TEST: true
      # TODO: remove this hack
      SCRIPT: L0_Unit_Tests_GPU_ASR

  L0_Unit_Tests_GPU_Audio:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'L0_Unit_Tests_GPU_Audio')
    with:
      RUNNER: self-hosted-azure-gpus-1
      TIMEOUT: 20
      IS_UNIT_TEST: true
      SCRIPT: L0_Unit_Tests_GPU_Audio

  L0_Unit_Tests_GPU_Common:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'L0_Unit_Tests_GPU_Common')
    with:
      RUNNER: self-hosted-azure-gpus-1
      IS_UNIT_TEST: true
      SCRIPT: L0_Unit_Tests_GPU_Common

  L0_Unit_Tests_GPU_LLM:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'L0_Unit_Tests_GPU_LLM')
    with:
      RUNNER: self-hosted-azure-gpus-1
      IS_UNIT_TEST: true
      SCRIPT: L0_Unit_Tests_GPU_LLM

  L0_Unit_Tests_GPU_VLM:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'L0_Unit_Tests_GPU_VLM')
    with:
      RUNNER: self-hosted-azure-gpus-1
      IS_UNIT_TEST: true
      SCRIPT: L0_Unit_Tests_GPU_VLM

  L0_Unit_Tests_GPU_Multimodal:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'L0_Unit_Tests_GPU_Multimodal')
    with:
      RUNNER: self-hosted-azure-gpus-1
      IS_UNIT_TEST: true
      SCRIPT: L0_Unit_Tests_GPU_Multimodal

  L0_Unit_Tests_GPU_TTS:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'L0_Unit_Tests_GPU_TTS')
    with:
      RUNNER: self-hosted-azure-gpus-1
      IS_UNIT_TEST: true
      SCRIPT: L0_Unit_Tests_GPU_TTS

  L0_Unit_Tests_GPU_Core:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'L0_Unit_Tests_GPU_Core')
    with:
      RUNNER: self-hosted-azure-gpus-1
      TIMEOUT: 20
      IS_UNIT_TEST: true
      SCRIPT: L0_Unit_Tests_GPU_Core

  L0_Unit_Tests_GPU_Hydra:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'L0_Unit_Tests_GPU_Hydra')
    with:
      RUNNER: self-hosted-azure-gpus-1
      IS_UNIT_TEST: true
      SCRIPT: L0_Unit_Tests_GPU_Hydra

  L0_Unit_Tests_GPU_Lightning:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'L0_Unit_Tests_GPU_Lightning')
    with:
      RUNNER: self-hosted-azure
      IS_UNIT_TEST: true
      SCRIPT: L0_Unit_Tests_GPU_Lightning

  L0_Unit_Tests_GPU_Others:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'L0_Unit_Tests_GPU_Others')
    with:
      RUNNER: self-hosted-azure-gpus-1
      IS_UNIT_TEST: true
      SCRIPT: L0_Unit_Tests_GPU_Others

  # L0: CPU unit tests
  L0_Unit_Tests_CPU_ASR:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'L0_Unit_Tests_CPU_ASR')
    with:
      RUNNER: self-hosted-azure-cpu
      TIMEOUT: 20
      IS_UNIT_TEST: true
      SCRIPT: L0_Unit_Tests_CPU_ASR

  L0_Unit_Tests_CPU_Audio:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'L0_Unit_Tests_CPU_Audio')
    with:
      RUNNER: self-hosted-azure-cpu
      IS_UNIT_TEST: true
      SCRIPT: L0_Unit_Tests_CPU_Audio

  L0_Unit_Tests_CPU_Common:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'L0_Unit_Tests_CPU_Common')
    with:
      RUNNER: self-hosted-azure-cpu
      TIMEOUT: 20
      IS_UNIT_TEST: true
      SCRIPT: L0_Unit_Tests_CPU_Common

  L0_Unit_Tests_CPU_LLM:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'L0_Unit_Tests_CPU_LLM')
    with:
      RUNNER: self-hosted-azure-cpu
      IS_UNIT_TEST: true
      SCRIPT: L0_Unit_Tests_CPU_LLM

  L0_Unit_Tests_CPU_VLM:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'L0_Unit_Tests_CPU_VLM')
    with:
      RUNNER: self-hosted-azure-cpu
      IS_UNIT_TEST: true
      SCRIPT: L0_Unit_Tests_CPU_VLM

  L0_Unit_Tests_CPU_Multimodal:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'L0_Unit_Tests_CPU_Multimodal')
    with:
      RUNNER: self-hosted-azure-cpu
      IS_UNIT_TEST: true
      SCRIPT: L0_Unit_Tests_CPU_Multimodal

  L0_Unit_Tests_CPU_TTS:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'L0_Unit_Tests_CPU_TTS')
    with:
      RUNNER: self-hosted-azure-cpu
      IS_UNIT_TEST: true
      SCRIPT: L0_Unit_Tests_CPU_TTS

  L0_Unit_Tests_CPU_Core:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'L0_Unit_Tests_CPU_Core')
    with:
      RUNNER: self-hosted-azure-cpu
      TIMEOUT: 20
      IS_UNIT_TEST: true
      SCRIPT: L0_Unit_Tests_CPU_Core

  L0_Unit_Tests_CPU_Hydra:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'L0_Unit_Tests_CPU_Hydra')
    with:
      RUNNER: self-hosted-azure-cpu
      IS_UNIT_TEST: true
      SCRIPT: L0_Unit_Tests_CPU_Hydra

  L0_Unit_Tests_CPU_Lightning:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'L0_Unit_Tests_CPU_Lightning')
    with:
      RUNNER: self-hosted-azure-cpu
      IS_UNIT_TEST: true
      SCRIPT: L0_Unit_Tests_CPU_Lightning

  L0_Unit_Tests_CPU_Others:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'L0_Unit_Tests_CPU_Others')
    with:
      RUNNER: self-hosted-azure-cpu
      IS_UNIT_TEST: true
      SCRIPT: L0_Unit_Tests_CPU_Others
