name: NeMo E2E Export Deploy Tests
on:
  workflow_call:
    inputs:
      test_to_run:
        required: true
        type: string
      image-name:
        required: false
        default: nemo_container_export_deploy
        type: string

jobs:
  build:
    uses: ./.github/workflows/_build_container.yml
    with:
      image-name: ${{ inputs.image-name }}
      dockerfile: Dockerfile.ci.export_deploy

  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - script: L0_Unit_Tests_GPU_Export_Deploy
            runner: ubuntu-latest
          - script: L0_Unit_Tests_CPU_Export_Deploy
            runner: ubuntu-latest
          - script: L0_Unit_Tests_Eval
            runner: ubuntu-latest
    needs: [build]
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.script }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ github.run_id }}
      - name: main
        uses: ${{ github.run_id }}/.github/actions/test-template
        with:
          runner: ${{ runner.name }}
          script: ${{ matrix.script }}
          is_unit_test: true
          tests_to_run: ${{ inputs.test_to_run }}
          image: ${{ inputs.image-name }}

  e2e-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Export tests
          - script: L2_NeMo_2_Export_HF_TRT_LLM
            runner: ubuntu-latest
          - script: L2_NeMo_2_Export_Deploy_Query_In_Framework
            runner: ubuntu-latest
          - script: L2_ONNX_TRT_LLM_Embedding_Export
            runner: ubuntu-latest
          - script: L2_NeMo_2_Export_TRT_LLM
            runner: ubuntu-latest
          - script: L2_NeMo_2_VLLM_EXPORT
            runner: ubuntu-latest
          - script: L2_NeMo_2_Export_In_Framework
            runner: ubuntu-latest
          - script: L2_NeMo_2_VLLM_VISION
            runner: ubuntu-latest
    needs: [unit-tests]
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.script }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ github.run_id }}
      - name: main
        uses: ${{ github.run_id }}/.github/actions/test-template
        with:
          runner: ${{ runner.name }}
          script: ${{ matrix.script }}
          tests_to_run: ${{ inputs.test_to_run }}
          image: ${{ inputs.image-name }}
