name: NeMo E2E TTS Tests
on:
  workflow_call:
    inputs:
      test_to_run:
        required: true
        type: string
      image-name:
        required: false
        default: nemo_container_tts
        type: string

jobs:
  tts-build:
    uses: ./.github/workflows/_build_container.yml
    with:
      image-name: ${{ inputs.image-name }}
      dockerfile: Dockerfile.ci

  tts-unit-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - script: L0_Unit_Tests_GPU_TTS
            runner: self-hosted-azure-gpus-1
          - script: L0_Unit_Tests_CPU_TTS
            runner: self-hosted-azure-cpu
    uses: ./.github/workflows/_test_template.yml
    needs: [tts-build]
    with:
      runner: ${{ matrix.runner }}
      script: ${{ matrix.script }}
      IS_UNIT_TEST: true
      TESTS_TO_RUN: ${{ inputs.test_to_run }}

  tts-e2e-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: self-hosted-azure-gpus-1
            script: L2_TTS_Fast_dev_runs_1_Tacotron_2
          - runner: self-hosted-azure
            script: L2_TTS_Fast_dev_runs_1_WaveGlow
          - runner: self-hosted-azure
            script: L2_TTS_Fast_dev_runs_1_FastPitch
          - runner: self-hosted-azure
            script: L2_TTS_Fast_dev_runs_1_Hifigan

    uses: ./.github/workflows/_test_template.yml
    needs: [tts-unit-tests]
    with:
      RUNNER: ${{ matrix.runner }}
      SCRIPT: ${{ matrix.script }}
      TESTS_TO_RUN: ${{ inputs.test_to_run }}
      IMAGE: ${{ inputs.image-name }}
      IS_OPTIONAL: ${{ matrix.is_optional || false }}
