# Copyright (c) 2020-2021, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: ~asr suite

on:
  workflow_call:
    inputs:
      test_to_run:
        type: string
        description: Tests to run
        required: true
jobs:
  L0_Unit_Tests_GPU_ASR:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(needs.pre-flight.outputs.test_to_run), 'L0_Unit_Tests_GPU_ASR')
    with:
      RUNNER: self-hosted-azure-gpus-1
      TIMEOUT: 20
      IS_UNIT_TEST: true
      SCRIPT: |-
        RUN_ID=${{ github.run_id }} bash tests/functional_tests/L0_Unit_Tests_GPU_ASR.sh

  L0_Unit_Tests_CPU_ASR:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'L0_Unit_Tests_CPU_ASR')
    with:
      RUNNER: self-hosted-azure-cpu
      TIMEOUT: 20
      IS_UNIT_TEST: true
      SCRIPT: |-
        RUN_ID=${{ github.run_id }} bash tests/functional_tests/L0_Unit_Tests_CPU_ASR.sh

  Unit_Tests_ASR:
    needs: [L0_Unit_Tests_GPU_ASR, L0_Unit_Tests_CPU_ASR]
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: exit 0

  # L2: ASR dev run
  ASR_dev_run_Speech_to_Text:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'ASR_dev_run_Speech_to_Text')
    needs: [Unit_Tests_ASR]
    with:
      RUNNER: self-hosted-azure-gpus-1
      SCRIPT: |-
        RUN_ID=${{ github.run_id }} 
        bash tests/functional_tests/ASR_dev_run_Speech_to_Text.sh

  ASR_dev_run_Speech_to_Text_WPE_CitriNet:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'ASR_dev_run_Speech_to_Text_WPE_CitriNet')
    needs: [Unit_Tests_ASR]
    with:
      RUNNER: self-hosted-azure-gpus-1
      SCRIPT: |-
        RUN_ID=${{ github.run_id }} 
        bash tests/functional_tests/ASR_dev_run_Speech_to_Text_WPE_CitriNet.sh

  ASR_dev_run_Speech_Pre-training_-_CitriNet:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'ASR_dev_run_Speech_Pre-training_-_CitriNet')
    needs: [Unit_Tests_ASR]
    with:
      RUNNER: self-hosted-azure-gpus-1
      SCRIPT: |-
        RUN_ID=${{ github.run_id }} bash tests/functional_tests/ASR_dev_run_Speech_Pre-training_-_CitriNet.sh

  Optional_ASR_dev_run_Speech_To_Text_Finetuning:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'Optional_ASR_dev_run_Speech_To_Text_Finetuning')
    needs: [Unit_Tests_ASR]
    with:
      RUNNER: self-hosted-azure-gpus-1
      SCRIPT: |-
        RUN_ID=${{ github.run_id }} bash tests/functional_tests/Optional_ASR_dev_run_Speech_To_Text_Finetuning.sh
      IS_OPTIONAL: true

  Optional_ASR_dev_run_Speech_To_Text_HF_Finetuning:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'Optional_ASR_dev_run_Speech_To_Text_HF_Finetuning')
    needs: [Unit_Tests_ASR]
    with:
      RUNNER: self-hosted-azure-gpus-1
      SCRIPT: |-
        RUN_ID=${{ github.run_id }} bash tests/functional_tests/Optional_ASR_dev_run_Speech_To_Text_HF_Finetuning.sh
      IS_OPTIONAL: true

  ASR_dev_run_Speech_to_Text_WPE_-_Conformer:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'ASR_dev_run_Speech_to_Text_WPE_-_Conformer')
    needs: [Unit_Tests_ASR]
    with:
      RUNNER: self-hosted-azure-gpus-1
      SCRIPT: |-
        RUN_ID=${{ github.run_id }} bash tests/functional_tests/ASR_dev_run_Speech_to_Text_WPE_-_Conformer.sh

  # L2: ASR dev run - part two
  ASR_dev_run-part_two_Speech_to_Text_WPE_-_Squeezeformer:
    uses: ./.github/workflows/_test_template.yml
    if: contains(fromJSON(inputs.test_to_run), 'ASR_dev_run-part_two_Speech_to_Text_WPE_-_Squeezeformer')
    needs: [Unit_Tests_ASR]
    with:
      RUNNER: self-hosted-azure-gpus-1
      SCRIPT: |-
        RUN_ID=${{ github.run_id }} bash tests/functional_tests/ASR_dev_run-part_two_Speech_to_Text_WPE_-_Squeezeformer.sh
