name: NeMo E2E Tests
on:
  workflow_call:
    inputs:
      test_to_run:
        required: true
        type: string

jobs:
  collections-asr-tests:
    strategy:
      matrix:
        include:
          - script: ASR_dev_run_Speech_to_Text
            runner: self-hosted-azure-gpus-1
          - script: ASR_dev_run_Speech_to_Text_WPE_CitriNet
            runner: self-hosted-azure-gpus-1
          - script: ASR_dev_run_Speech_Pre-training_-_CitriNet
            runner: self-hosted-azure-gpus-1
          - script: Optional_ASR_dev_run_Speech_To_Text_Finetuning
            runner: self-hosted-azure-gpus-1
            is_optional: true
          - script: Optional_ASR_dev_run_Speech_To_Text_HF_Finetuning
            runner: self-hosted-azure-gpus-1
            is_optional: true
          - script: ASR_dev_run_Speech_to_Text_WPE_-_Conformer
            runner: self-hosted-azure-gpus-1
          - script: ASR_dev_run-part_two_Speech_to_Text_WPE_-_Squeezeformer
            runner: self-hosted-azure-gpus-1
          - script: L2_Speech_to_Text_EMA
            runner: self-hosted-azure
          - script: L2_Speech_to_Text_AED
            runner: self-hosted-azure-gpus-1
          - script: L2_Speaker_dev_run_Speaker_Recognition
            runner: self-hosted-azure-gpus-1
          - script: L2_Speaker_dev_run_Speaker_Diarization
            runner: self-hosted-azure-gpus-1
          - script: L2_Speaker_dev_run_EndtoEnd_Speaker_Diarization_Sortformer
            runner: self-hosted-azure-gpus-1
          - script: L2_Speaker_dev_run_EndtoEnd_Diarizer_Inference
            runner: self-hosted-azure
          - script: L2_Speaker_dev_run_Speech_to_Label
            runner: self-hosted-azure-gpus-1
          - script: L2_Speaker_dev_run_Speaker_Diarization_with_ASR_Inference
            runner: self-hosted-azure
          - script: L2_Speaker_dev_run_Clustering_Diarizer_Inference
            runner: self-hosted-azure
          - script: L2_Speaker_dev_run_Neural_Diarizer_Inference
            runner: self-hosted-azure
          - script: L2_Speaker_dev_run_Multispeaker_ASR_Data_Simulation
            runner: self-hosted-azure
          - script: L2_ASR_Multi-dataloader_dev_run_Speech_to_Text_multi-dataloader
            runner: self-hosted-azure-gpus-1
          - script: L2_ASR_Multi-dataloader_dev_run_Speech_to_Label_multi-dataloader
            runner: self-hosted-azure-gpus-1
          - script: L2_ASR_Adapters_Linear_Adapters
            runner: self-hosted-azure-gpus-1
          - script: L2_ASR_Adapters_RelPos_MHA_Adapters
            runner: self-hosted-azure-gpus-1
          - script: L2_Speech_Estimate_Duration_Bins
            runner: self-hosted-azure
          - script: L2_Speech_Batch_Size_OOMptimizer
            runner: self-hosted-azure
          - script: Optional_L2_Speech_Batch_Size_OOMptimizer_Canary
            runner: self-hosted-azure
            is_optional: true
          - script: L2_Speech_Transcription_Speech_to_Text_Transcribe
            runner: self-hosted-azure
          - script: L2_Speech_Transcription_Canary_Transcribe_Full_Manifest
            runner: self-hosted-azure
          - script: L2_Speech_Transcription_Canary_Transcribe_With_Prompt
            runner: self-hosted-azure
          - script: L2_Speech_Transcription_Canary_Transcribe_Audio_Dir
            runner: self-hosted-azure
            is_optional: true
          - script: L2_Longform_Speech_Transcription_Canary_Chunked_Infer_from_Audio_Dir
            runner: self-hosted-azure
          - script: L2_Longform_Speech_Transcription_with_TimeStamps_Canary_Chunked_Infer_from_Audio_Dir
            runner: self-hosted-azure
          - script: L2_Longform_Speech_Transcription_with_TimeStamps_Canary_Chunked_Infer_from_Manifest
            runner: self-hosted-azure
          - script: L2_Segmentation_Tool_Parallel_ctc_segmentation_test_L2_Eng_CitriNet_with_wav
            runner: self-hosted-azure
          - script: L2_Segmentation_Tool_Parallel_ctc_segmentation_test_L2_Ru_QN_with_mp3
            runner: self-hosted-azure
          - script: L2_G2P_Models_G2P_Conformer_training_evaluation_and_inference
            runner: self-hosted-azure
          - script: L2_G2P_Models_HeteronymClassificationModel_training_evaluation_and_inference
            runner: self-hosted-azure
          - script: L2_HF_Transformer_SpeechLM_SFT_2gpu
            runner: self-hosted-azure
          - script: Speech_Checkpoints_tests
            runner: self-hosted-azure-gpus-1
          - script: L2_SpeechLM_LoRA_TP1PP1_MBS2
            runner: self-hosted-azure
    uses: ./.github/workflows/_test_template.yml
    with:
      RUNNER: ${{ matrix.runner }}
      SCRIPT: ${{ matrix.script }}
      IS_OPTIONAL: ${{ matrix.is_optional || false }}

  collections-nmt-tests:
    strategy:
      matrix:
        include:
          - script: L2_NMT_Attention_is_All_You_Need_Training_NMT_Training_Post-LN
            runner: self-hosted-azure-gpus-1
          - script: L2_NMT_Attention_is_All_You_Need_Training_NMT_Training_Pre-LN
            runner: self-hosted-azure-gpus-1
          - script: L2_NMT_Attention_is_All_You_Need_Training_NMT_Multi-Validation
            runner: self-hosted-azure-gpus-1
          - script: L2_NMT_Attention_is_All_You_Need_Inference
            runner: self-hosted-azure
          - script: L2_NMT_Attention_is_All_You_Need_Finetuning
            runner: self-hosted-azure-gpus-1
          - script: L2_NMT_Tarred_Dataset_Creation_Auto_Tarred_Dataset_Creation
            runner: self-hosted-azure-gpus-1
          - script: L2_NMT_Tarred_Dataset_Creation_Script_Tarred_Dataset_Creation
            runner: self-hosted-azure
          - script: L2_Megatron_NMT_Training_TP2
            runner: self-hosted-azure
    uses: ./.github/workflows/_test_template.yml
    with:
      RUNNER: ${{ matrix.runner }}
      SCRIPT: ${{ matrix.script }}
      IS_OPTIONAL: ${{ matrix.is_optional || false }}

  collections-tts-tests:
    strategy:
      matrix:
        include:
          - script: L2_TTS_Fast_dev_runs_1_Tacotron_2
            runner: self-hosted-azure-gpus-1
          - script: L2_TTS_Fast_dev_runs_1_WaveGlow
            runner: self-hosted-azure
          - script: L2_TTS_Fast_dev_runs_1_FastPitch
            runner: self-hosted-azure
          - script: L2_TTS_Fast_dev_runs_1_Hifigan
            runner: self-hosted-azure
    uses: ./.github/workflows/_test_template.yml
    with:
      RUNNER: ${{ matrix.runner }}
      SCRIPT: ${{ matrix.script }}

  collections-vlm-tests:
    strategy:
      matrix:
        include:
          - script: L2_VLM_HF_Transformer_PEFT
            runner: self-hosted-azure-gpus-1
          - script: L2_VLM_HF_Transformer_PEFT_FSDP2
            runner: self-hosted-azure
          - script: L2_VLM_HF_Transformer_PEFT_4bit
            runner: self-hosted-azure-gpus-1
          - script: L2_VLM_HF_Transformer_SFT_FSDP2
            runner: self-hosted-azure
          - script: L2_NeMo_2_LLAVA_NEXT_MOCK_TRAINING
            runner: self-hosted-azure
          - script: L2_NeMo_2_LLAVA_NEXT_HF_CONVERSION
            runner: self-hosted-azure
          - script: L2_NeMo_2_LLAVA_NEXT_ENERGON_TRAIN
            runner: self-hosted-azure
          - script: L2_NeMo_2_LLAVA_NEXT_ENERGON_PACKED_TRAIN
            runner: self-hosted-azure
          - script: L2_NeMo_2_CLIP_PRETRAIN
            runner: self-hosted-azure
          - script: L2_NeMo_2_CLIP_INFER
            runner: self-hosted-azure
          - script: L2_Stable_Diffusion_Training
            runner: self-hosted-azure-gpus-1
          - script: L2_NeMo_2_NEVA_MOCK_PRETRAIN_TP2
            runner: self-hosted-azure
          - script: L2_NeMo_2_NEVA_MOCK_PRETRAIN_PP2
            runner: self-hosted-azure
          - script: L2_NeMo_2_NEVA_MOCK_PRETRAIN_CP2
            runner: self-hosted-azure
          - script: L2_NeMo_2_NEVA_MOCK_FINETUNE_TP2
            runner: self-hosted-azure
          - script: L2_NeMo_2_NEVA_MOCK_FINETUNE_PP2
            runner: self-hosted-azure
          - script: L2_NeMo_2_NEVA_MOCK_FINETUNE_CP2
            runner: self-hosted-azure
          - script: L2_NeMo_2_NEVA_LOAD_GENERATE
            runner: self-hosted-azure
    uses: ./.github/workflows/_test_template.yml
    with:
      RUNNER: ${{ matrix.runner }}
      SCRIPT: ${{ matrix.script }}

  collections-llm-tests:
    strategy:
      matrix:
        include:
          - script: L2_NeMo_2_GPT_Pretraining_no_transformer_engine
            runner: self-hosted-azure
          - script: L2_NeMo_2_llama3_pretraining_recipe
            runner: self-hosted-azure
          - script: L2_NeMo_2_llama3_fault_tolerance_plugin
            runner: self-hosted-azure
          - script: L2_NeMo_2_llama3_straggler_detection
            runner: self-hosted-azure
          - script: L2_NeMo_2_GPT_DDP_Param_Parity_check
            runner: self-hosted-azure
          - script: L2_NeMo_2_Hyena_Conversion_from_HF
            runner: self-hosted-azure
          - script: L2_NeMo_2_Hyena_DDP_Pretraining_Test
            runner: self-hosted-azure
          - script: L2_NeMo_2_SSM_Pretraining
            runner: self-hosted-azure-gpus-1
          - script: L2_NeMo_2_SSM_Finetuning
            runner: self-hosted-azure-gpus-1
          - script: L2_NeMo_2_HF_MODEL_IMPORT
            runner: self-hosted-azure
          - script: L2_NeMo_2_jit_callback
            runner: self-hosted-azure
          - script: L2_NeMo_2_T5_Pretraining
            runner: self-hosted-azure
          - script: L2_NeMo_2_T5_Finetuning
            runner: self-hosted-azure
          - script: L2_NeMo_2_T5_LoRA
            runner: self-hosted-azure
          - script: L2_NeMo_2_BERT_Pretraining_Megatron
            runner: self-hosted-azure
          - script: L2_NeMo_2_BERT_Pretraining_HuggingFace
            runner: self-hosted-azure
          - script: L2_NeMo_2_GPT_SFT_TP1PP1_MBS1
            runner: self-hosted-azure
          - script: L2_NeMo_2_GPT_SFT_TP1PP1_MBS2
            runner: self-hosted-azure
          - script: L2_NeMo_2_GPT_SFT_TP1PP2_MBS2
            runner: self-hosted-azure
          - script: L2_NeMo_2_GPT_SFT_TP2PP1_MBS2
            runner: self-hosted-azure
          - script: L2_NeMo_2_GPT_SFT_TP1PP1_MBS1_PACKED
            runner: self-hosted-azure
          - script: L2_NeMo_2_GPT_LoRA_TP1PP1_MBS1
            runner: self-hosted-azure
          - script: L2_NeMo_2_GPT_LoRA_TP1PP1_MBS2
            runner: self-hosted-azure
          - script: L2_NeMo_2_GPT_LoRA_TP1PP2_MBS2
            runner: self-hosted-azure
          - script: L2_NeMo_2_GPT_LoRA_TP2PP1_MBS2
            runner: self-hosted-azure
          - script: L2_NeMo_2_GPT_LoRA_TP1PP1_MBS1_PACKED
            runner: self-hosted-azure
          - script: L2_NeMo_2_GPT_DoRA_TP1PP1_MBS1_PACKED
            runner: self-hosted-azure
          - script: L2_NeMo_2_GPT_CLoRA_TP1PP1_MBS1_PACKED
            runner: self-hosted-azure
          - script: L2_NeMo_2_GPT_LoRA_TP1PP1_MBS1_Chat
            runner: self-hosted-azure
          - script: L2_NeMo_2_Mixtral_Pretraining
            runner: self-hosted-azure
          - script: L2_NeMo_2_Mixtral_LoRA_EP2PP1_MBS2_exclude
            runner: self-hosted-azure
          - script: L2_NeMo_2_Mixtral_LoRA_EP2PP1_MBS2
            runner: self-hosted-azure
          - script: L2_NeMo_2_Mixtral_LoRA_TP1PP1_MBS1
            runner: self-hosted-azure
          - script: L2_NeMo_2_Mixtral_LoRA_TP2PP1_MBS1
            runner: self-hosted-azure
          - script: L2_NeMo_2_Mistral_LoRA_TP1PP1_MBS1
            runner: self-hosted-azure
          - script: L2_NeMo_2_Mistral_LoRA_TP1PP1_MBS1_exclude
            runner: self-hosted-azure
          - script: L2_NeMo_2_Mistral_LoRA_TP2PP1_MBS1
            runner: self-hosted-azure
          - script: L2_HF_Transformer_PEFT_notebook
            runner: self-hosted-azure
          - script: L2_HF_Transformer_PEFT
            runner: self-hosted-azure-gpus-1
          - script: L2_HF_Transformer_PEFT_nemorun
            runner: self-hosted-azure-gpus-1
          - script: L2_HF_Transformer_PEFT_2gpu
            runner: self-hosted-azure
          - script: L2_HF_Transformer_PEFT_2gpu_FSDP2_liger
            runner: self-hosted-azure
          - script: L2_HF_Transformer_PEFT_2gpu_FSDP2_fp8
            runner: azure-gpu-vm-runner1-
            is_optional: true
          - script: L2_HF_Transformer_PEFT_2gpu_FSDP2
            runner: self-hosted-azure
          - script: L2_HF_Transformer_PEFT_2gpu_nemorun
            runner: self-hosted-azure
          - script: L2_HF_Transformer_SFT_2gpu
            runner: self-hosted-azure
          - script: L2_HF_Transformer_SFT_2gpu_FSDP2
            runner: self-hosted-azure
          - script: L2_HF_Transformer_SFT_2gpu_FSDP2_fp8
            runner: azure-gpu-vm-runner1-h100
            is_optional: true
          - script: L2_HF_Transformer_SFT_2gpu_nemorun
            runner: self-hosted-azure
          - script: L2_HF_Transformer_SFT_2gpu_nemorun_fsdp2
            runner: self-hosted-azure
          - script: L2_HF_Transformer_SFT_FSDP2_2gpu
            runner: self-hosted-azure
          - script: L2_HF_Transformer_PT_2gpu
            runner: self-hosted-azure
          - script: L2_HF_Transformer_PT_2gpu_nemorun
            runner: self-hosted-azure
          - script: L2_HF_Transformer_PT
            runner: self-hosted-azure-gpus-1
          - script: L2_HF_Transformer_PT_nemorun
            runner: self-hosted-azure-gpus-1
          - script: L2_HF_Transformer_SFT_notebook
            runner: self-hosted-azure
          - script: L2_HF_Transformer_SFT
            runner: self-hosted-azure-gpus-1
          - script: L2_HF_Transformer_SFT_nemorun
            runner: self-hosted-azure-gpus-1
          - script: L2_HF_Transformer_SFT_TE_Acceleration
            runner: self-hosted-azure-gpus-1
          - script: L2_HF_Transformer_PT_TE_Acceleration
            runner: self-hosted-azure-gpus-1
    uses: ./.github/workflows/_test_template.yml
    with:
      RUNNER: ${{ matrix.runner }}
      SCRIPT: ${{ matrix.script }}
      IS_OPTIONAL: ${{ matrix.is_optional || false }}

  core-tests:
    strategy:
      matrix:
        include:
          - script: L0_Setup_Test_Data_And_Models
            runner: self-hosted-azure
          - script: L2_NeMo_2_VLLM_EXPORT
            runner: self-hosted-azure
          - script: L2_NeMo_2_EVAL
            runner: self-hosted-azure-gpus-1
          - script: L2_NeMo_2_Auto_Configurator_llama_TP1_PP1_MBS124
            runner: self-hosted-azure-gpus-1
          - script: L2_NeMo_2_Auto_Configurator_bert_TP1_PP1_MBS124
            runner: self-hosted-azure-gpus-1
          - script: L2_NeMo_2_Auto_Configurator_t5_TP1_PP1_MBS124
            runner: self-hosted-azure-gpus-1
          - script: L2_NeMo_2_Conversion_Test_Baichuan2
            runner: self-hosted-azure
          - script: L2_NeMo_2_Conversion_Test_ChatGLM
            runner: self-hosted-azure
          - script: L2_NeMo_2_Conversion_Test_DeepSeek
            runner: self-hosted-azure
          - script: L2_NeMo_2_Conversion_Test_Gemma
            runner: self-hosted-azure
          - script: L2_NeMo_2_Conversion_Test_Gemma2
            runner: self-hosted-azure
          - script: L2_NeMo_2_Conversion_Test_Mistral
            runner: self-hosted-azure
          - script: L2_NeMo_2_Conversion_Test_Llama
            runner: self-hosted-azure
          - script: L2_NeMo_2_Conversion_Test_Llama_Embedding
            runner: self-hosted-azure
          - script: L2_NeMo_2_Conversion_Test_Nemotron
            runner: self-hosted-azure
          - script: L2_NeMo_2_Conversion_Test_Phi3Mini
            runner: self-hosted-azure
          - script: L2_NeMo_2_Conversion_Test_Qwen2
            runner: self-hosted-azure
          - script: L2_NeMo_2_Conversion_Test_Starcoder
            runner: self-hosted-azure
          - script: L2_NeMo_2_Conversion_Test_Starcoder2
            runner: self-hosted-azure
          - script: L2_NeMo_2_Conversion_Test_BERT
            runner: self-hosted-azure
    uses: ./.github/workflows/_test_template.yml
    with:
      RUNNER: ${{ matrix.runner }}
      SCRIPT: ${{ matrix.script }}

  other-tests:
    strategy:
      matrix:
        include:
          - script: L2_NEMO_2_MLLAMA_Inference
            runner: self-hosted-azure-gpus-1
          - script: L2_NeMo_2_MLLAMA_MOCK_FINETUNE_TP2
            runner: self-hosted-azure
          - script: L2_NEMO_2_LoRA_MERGE
            runner: self-hosted-azure
          - script: L2_NEMO_2_LoRA_Export
            runner: self-hosted-azure-gpus-1
          - script: L2_NEMO_2_LoRA_Inference
            runner: self-hosted-azure-gpus-1
          - script: L2_NeMo_2_NeMo_Mcore_Mixtral_bitexact
            runner: self-hosted-azure
          - script: L2_NeMo_2_Automodel_PTQ_trtllm
            runner: self-hosted-azure
          - script: L2_NeMo_2_Automodel_PTQ_hf
            runner: self-hosted-azure
          - script: L2_NeMo_2_PTQ_Llama2_FP8_trtllm
            runner: self-hosted-azure
          - script: L2_NeMo_2_PTQ_Llama2_FP8_nemo
            runner: self-hosted-azure
          - script: L2_NeMo_2_Distill_Llama3_TP1PP2
            runner: self-hosted-azure
          - script: L2_NeMo_2_Prune_Llama_TP1PP2
            runner: self-hosted-azure
          - script: L2_NeMo_2_Export_In_Framework
            runner: self-hosted-azure

    uses: ./.github/workflows/_test_template.yml
    with:
      RUNNER: ${{ matrix.runner }}
      SCRIPT: ${{ matrix.script }}
      IS_OPTIONAL: ${{ matrix.is_optional || false }}
