name: gh-docs-build
on:
  push:
  pull_request:
    paths:
      - "**"
jobs:
  deploy:
    runs-on: ubuntu-latest

    container:
      image: squidfunk/mkdocs-material

    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages

      - run: git config --global --add safe.directory /__w/NeMo/NeMo
      - run: mkdocs gh-deploy --force

