name: gh-docs-build
on:
  push:
  pull_request:
    paths:
      - "**"

# Set the access for individual scopes, or use permissions: write-all
permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  deployments: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    container:
      image: squidfunk/mkdocs-material

    steps:
      - name: "Check if user has write access"
        uses: "lannonbr/repo-permission-check-action@2.0.0"
        with:
          permission: "write"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        with:
          ref: gh-pages

      - run: git config --global --add safe.directory /__w/NeMo/NeMo
      - run: mkdocs gh-deploy --force

