name: CI-Import-Check

on:
  push:
  pull_request:
    paths:
      - "**"

jobs:
  build-nemo:
    runs-on: ubuntu-latest

    # Check https://hub.docker.com/r/pytorch/pytorch/tags for latest tags
    container:
      image: pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime

    steps:
    - uses: actions/checkout@v2
    - name: Update base dependencies
      run: |
        apt-get update && apt-get install -y build-essential
        apt-get install -y libsndfile1 make
    - name: Install nemo dependencies
      id: nemo-wheel
      run:  |
        pip install Cython
        # install test requirements
        pip install -r requirements/requirements_test.txt
        # Build nemo as a wheel
        pip install build
        python -m build --no-isolation --wheel
        # Preserve wheel location
        DIST_FILE=$(find ./dist -name "*.whl" | head -n 1)
        echo "::set-output name=DIST_FILE::${DIST_FILE}"
    - name: Upload wheel as artifact
      uses: actions/upload-artifact@v2
      with:
        name: nemo-wheel-file
        path: ${{ steps.nemo-wheel.outputs.DIST_FILE }}
    outputs:
      dist_file: ${{ steps.nemo-wheel.outputs.DIST_FILE }}

    
  test-asr-imports:
    needs: build-nemo
    runs-on: ubuntu-latest
    container:
      image: pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
        with:
          name: nemo-wheel-file
          path: ./dist
    - name: Test ASR Domain Imports
      run: |
        # Install NeMo Domain
        pip install "${{ needs.build-nemo.outputs.dist_file }}[asr]"
        # Run import checks
        python tests/core_ptl/check_imports.py --domain "asr"
        # Uninstall NeMo
        pip uninstall -y nemo_toolkit

  test-tts-imports:
    needs: build-nemo
    runs-on: ubuntu-latest
    container:
      image: pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
        with:
          name: nemo-wheel-file
          path: ./dist
    - name: Test TTS Domain Imports
      run: |
        # Install NeMo Domain
        pip install "${{ needs.build-nemo.outputs.dist_file }}[tts]"
        # Run import checks
        python tests/core_ptl/check_imports.py --domain "tts"
        # Uninstall NeMo
        pip uninstall -y nemo_toolkit

  test-nlp-imports:
    needs: build-nemo
    runs-on: ubuntu-latest
    container:
      image: pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
        with:
          name: nemo-wheel-file
          path: ./dist
    - name: Test NLP Domain Imports
      run: |
        # Install NeMo Domain
        pip install "${{ needs.build-nemo.outputs.dist_file }}[nlp]"
        # Run import checks
        python tests/core_ptl/check_imports.py --domain "nlp"
        # Uninstall NeMo
        pip uninstall -y nemo_toolkit

