name: CI-Import-Check

on:
  pull_request:
    paths:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# Check https://hub.docker.com/r/pytorch/pytorch/tags for latest tags
jobs:
  test-imports-macos:
    name: test-${{ matrix.collection }}-import-${{ matrix.os }}-py${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        collection:
          - all
          - asr
          - tts
        python: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python }}"
      - name: Build wheel
        id: nemo-wheel
        run: |
          # Build nemo as a wheel
          pip install build
          python -m build --wheel

          # Preserve wheel location
          DIST_FILE=$(find ./dist -name "*.whl" | head -n 1)
          echo "DIST_FILE=${DIST_FILE}" | tee -a "$GITHUB_OUTPUT"

      - name: Install NeMo
        run: |
          # Install NeMo Domain
          pip install --no-cache-dir "${{ steps.nemo-wheel.outputs.DIST_FILE }}"
          pip install --no-cache-dir "${{ steps.nemo-wheel.outputs.DIST_FILE }}[${{ matrix.collection }}]"

      - name: Run ${{ matrix.collection }} checks
        if: ${{ contains(fromJSON('["asr", "tts", "nl"]'), matrix.collection) }}
        run: |
          # install test requirements
          pip install --no-cache-dir "${{ steps.nemo-wheel.outputs.DIST_FILE }}[test]"

          # Run import checks
          python tests/core_ptl/check_imports.py --domain "${{ matrix.collection }}"

  test-imports-linux:
    name: test-${{ matrix.collection }}-import-${{ matrix.os }}-py${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        collection:
          - import: asr
            image: ["ubuntu:22.04"]
          - import: nlp
            image: ["nvcr.io/nvidia/pytorch:25.01-py3"]
          - import: asr
            image: ["ubuntu:22.04"]
        python: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python }}"
      - name: Build wheel
        id: nemo-wheel
        run: |
          # Build nemo as a wheel
          pip install build
          python -m build --wheel

          # Preserve wheel location
          DIST_FILE=$(find ./dist -name "*.whl" | head -n 1)
          echo "DIST_FILE=${DIST_FILE}" | tee -a "$GITHUB_OUTPUT"

      - name: Install NeMo
        run: |
          # Install NeMo Domain
          pip install --no-cache-dir "${{ steps.nemo-wheel.outputs.DIST_FILE }}"
          pip install --no-cache-dir "${{ steps.nemo-wheel.outputs.DIST_FILE }}[${{ matrix.collection }}]"

      - name: Run ${{ matrix.collection }} checks
        if: ${{ contains(fromJSON('["asr", "tts", "nl"]'), matrix.collection) }}
        run: |
          # install test requirements
          pip install --no-cache-dir "${{ steps.nemo-wheel.outputs.DIST_FILE }}[test]"

          # Run import checks
          python tests/core_ptl/check_imports.py --domain "${{ matrix.collection }}"
