# Regularly updates the CI container
name: MCore Tag Bump Bot
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  mcore:
    uses: NVIDIA/NeMo-FW-CI-templates/.github/workflows/_bump_dockerfile.yml@ko3n1g/ci/bump-file
    with:
      source-repository: NVIDIA/Megatron-LM
      source-ref: main
      argument: MCORE_TAG
      file: reinstall.sh
      base-branch: weekly-bump
      cicd-label: Run CICD
      pr-reviewers: 'pablo-garay'
    secrets:
      PAT: ${{ secrets.PAT }}
