# Regularly updates the CI container
name: Megatron Tag Bump Bot
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  update-weekly-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Merge main back to weekly-bump
        run: |
          git fetch --unshallow
          # Try to checkout and pull existing branch, create new one if it doesn't exist
          if git ls-remote --exit-code origin weekly-bump; then
            git checkout weekly-bump
            git pull origin weekly-bump
            git merge --no-ff main -m "chore: Auto-merge main back to dev"
          else
            git checkout -b weekly-bump main
          fi
          git push -u origin weekly-bump

  mcore:
    uses: NVIDIA/NeMo-FW-CI-templates/.github/workflows/_bump_yamlfile.yml@v0.21.5
    needs: [update-weekly-branch]
    with:
      source-repository: NVIDIA/Megatron-LM
      source-ref: main
      yaml-path: '."vcs-dependencies"."megatron-lm".ref'
      file: requirements/manifest.json
      base-branch: weekly-bump
      cicd-labels: Run CICD,no-fail-fast
      pr-reviewers: "chtruong814"
    secrets:
      PAT: ${{ secrets.PAT }}

  # notify:
  #   if: failure()
  #   runs-on: ubuntu-latest
  #   needs: [update-weekly-branch, mcore]
  #   steps:
  #     - name: Notify
  #       env:
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  #         SLACK_WEBHOOK_ADMIN: <!subteam^${{ secrets.SLACK_WEBHOOK_ADMIN }}>
  #         GITHUB_RUN_ID: ${{ github.run_id }}
  #         GITHUB_REPOSITORY: ${{ github.repository }}
  #       run: |
  #         curl -X POST \
  #           -H 'Content-type: application/json' \
  #           --data "{\"text\":\":robot_joy: <https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}|Mcore-bump-bot workflow> failed. Please fix manually.\n\ncc ${SLACK_WEBHOOK_ADMIN}\"}" \
  #           $SLACK_WEBHOOK
