# Regularly updates the CI container
name: MCore Tag Bump Bot
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  bump-mcore:
    uses: NVIDIA/NeMo-FW-CI-templates/.github/workflows/_bump_dockerfile.yml@ko3n1g/feat/bump-dockerfile
    with:
      source-repository: NVIDIA/Megatron-LM
      source-ref: main
      build-arg: MCORE_TAG
      dockerfile: Dockerfile.ci
      base-branch: main
      cicd-label: Run CICD
      pr-reviewers: 'pablo-garay'
