# Regularly updates the CI container
name: Reboots VMs in a controlled way
on:
  schedule:
    - cron: 0 0 * * *
  pull_request:

jobs:
  main:
    runs-on: ${{ matrix.vm }}
    # environment: main
    strategy:
      fail-fast: false
      matrix:
        vm: 
          - azure-gpu-vm-runner1
          - azure-gpu-vm-runner-1gpu-a
          - azure-gpu-vm-runner-1gpu-c
          - azure-gpu-vm-runner1-h100
          - azure-gpu-vm-runner2
          - azure-gpu-vm-runner6
          - azure-gpu-vm-runner7
    steps:
      - name: Reboot
        run: |
          echo ${{ secrets.VM_KEY }} | sudo -S reboot -h now

  wait:
    needs: main
    runs-on: ubuntu-latest
    if: always()
    steps: 
      - name: Wait for VMs to come back
        run: sleep 300

  test:
    needs: wait
    runs-on: ${{ matrix.vm }}
    # environment: main
    if: always()
    strategy:
      fail-fast: false
      matrix:
        vm: 
          - azure-gpu-vm-runner1
          - azure-gpu-vm-runner-1gpu-a
          - azure-gpu-vm-runner-1gpu-c
          - azure-gpu-vm-runner1-h100
          - azure-gpu-vm-runner2
          - azure-gpu-vm-runner6
          - azure-gpu-vm-runner7
    steps:
      - name: Check nvidia-smi
        run: |
          docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi