name: "Prerelease"

on:
  workflow_dispatch:
    inputs:
      prerelease_sha:
        type: string
        description: "Commit SHA for prerelease tag (default: HEAD main)"
        required: false
  pull_request:
    
jobs:
  prerelease:
    uses: NVIDIA/NeMo-FW-CI-templates/.github/workflows/_prerelease_tag.yml@ko3n1g/feat/pre-release-tag
    with:
      name_of_library: NeMo-Toolkit
      prerelease_sha: ${{ inputs.prerelease_sha || github.sha }}
      python_package: nemo
    secrets:
      SLACK_RELEASE_ENDPOINT: ${{ secrets.SLACK_RELEASE_ENDPOINT }}
      PAT: ${{ secrets.PAT }}
