name: "NeMo Code release"

on:
  workflow_dispatch:
    inputs:
      branch: 
        description: Branch to release
        required: true
        type: string

jobs: 
  release:
    uses: NVIDIA/NeMo-FW-CI-templates/.github/workflows/_release_library.yml@v0.8.0
    with:
      image-name: 
        required: true
        description: Name of image to build & push
        type: string
      build-args: 
        required: false
        description: Additional build args to use
        type: string
      dockerfile:
        required: true
        description: Path to dockerfile
        type: string
      image-label:
        required: false
        description: Image label for pruning
        type: string
      prune-filter-timerange:
        required: false
        description: "Go duration strings (e.g. 10m, 1h30m) computed relative to the daemon machine's time"
        type: string
        default: 24h
      python-package:
        type: string
        description: Name of Python package
      container-workdir:
        type: string
        description: Location of Python package
      library-name:
        type: string
        description: Name of Nemo library
    secrets:
      TWINE_USERNAME:
        required: true
      TWINE_PASSWORD:
        required: true
      SLACK_RELEASE_ENDPOINT:
        required: true