sample_rate: 44100
win_length: 2048
hop_length: 512

mel:
  _target_: nemo.collections.tts.parts.preprocessing.features.MelSpectrogramFeaturizer
  sample_rate: ${sample_rate}
  win_length: ${win_length}
  hop_length: ${hop_length}
  lowfreq: 0
  highfreq: null

pitch:
  _target_: nemo.collections.tts.parts.preprocessing.features.PitchFeaturizer
  sample_rate: ${sample_rate}
  win_length: ${win_length}
  hop_length: ${hop_length}
  pitch_fmin: 60
  pitch_fmax: 640
